
import { ReceiptItem, LanguageCode } from './geminiService';
import { VoxelModel } from './voxelTypes';
import { bathroomVanity } from './blueprints/bathroomVanity';
import { sofa } from './blueprints/sofa';
import { minimalistFourDoorWardrobe } from './blueprints/minimalistFourDoorWardrobe';
import { luxuryKitchenSuite } from './blueprints/luxuryKitchenSuite';
import { modernRefrigerator } from './blueprints/modernRefrigerator';
import { showerBathtub } from './blueprints/showerBathtub';
import { modernTVStand } from './blueprints/modernTVStand';
import { minimalistTV } from './blueprints/minimalistTV';
import { standardBed } from './blueprints/standardBed';
import { bedsideTable } from './blueprints/bedsideTable';
import { classicalLamp } from './blueprints/classicalLamp';
import { studyDesk } from './blueprints/studyDesk';
import { simpleToilet } from './blueprints/simpleToilet'; 
import { chair } from './blueprints/chair'; 

export const FURNITURE_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  'zh-CN': {
    'default-Bed': '双人床',
    'default-StudyDesk': '书桌',
    'default-chair': '椅子',
    'default-Table': '茶几',
    'default-Bedsidetable': '左床头柜',
    'default1-Bedsidetable': '右床头柜',
    'default-lamp': '左台灯',
    'default-Bedsidelamp': '右台灯',
    'default-sofa': '主沙发',
    'default1-sofa': '单人位A',
    'default2-sofa': '单人位B',
    'default-wasthsink': '洗手台',
    'default-Toilet': '马桶',
    'default-kitchenStuie': '集成厨房',
    'default-Refrigerator': '冰箱',
    'default1-Wardrobe': '白色衣柜',
    'default-Wardrobe': '木质衣柜',
    'default-TV Stand': '电视柜',
    'default-TV': '智能电视',
    'default-Bathtub': '淋浴浴缸'
  },
  'en': {
    'default-Bed': 'Double Bed',
    'default-StudyDesk': 'Study Desk',
    'default-chair': 'Chair',
    'default-Table': 'Coffee Table',
    'default-Bedsidetable': 'Left Nightstand',
    'default1-Bedsidetable': 'Right Nightstand',
    'default-lamp': 'Left Lamp',
    'default-Bedsidelamp': 'Right Lamp',
    'default-sofa': 'Main Sofa',
    'default1-sofa': 'Armchair A',
    'default2-sofa': 'Armchair B',
    'default-wasthsink': 'Vanity Sink',
    'default-Toilet': 'Toilet',
    'default-kitchenStuie': 'Kitchen Suite',
    'default-Refrigerator': 'Fridge',
    'default1-Wardrobe': 'White Wardrobe',
    'default-Wardrobe': 'Wood Wardrobe',
    'default-TV Stand': 'TV Stand',
    'default-TV': 'Smart TV',
    'default-Bathtub': 'Shower Tub'
  },
  'fr': {
    'default-Bed': 'Lit Double',
    'default-StudyDesk': 'Bureau',
    'default-chair': 'Chaise',
    'default-Table': 'Table Basse',
    'default-Bedsidetable': 'Table de Chevet G',
    'default1-Bedsidetable': 'Table de Chevet D',
    'default-lamp': 'Lampe G',
    'default-Bedsidelamp': 'Lampe D',
    'default-sofa': 'Canapé Principal',
    'default1-sofa': 'Fauteuil A',
    'default2-sofa': 'Fauteuil B',
    'default-wasthsink': 'Lavabo',
    'default-Toilet': 'Toilettes',
    'default-kitchenStuie': 'Cuisine Intégrée',
    'default-Refrigerator': 'Réfrigérateur',
    'default1-Wardrobe': 'Armoire Blanche',
    'default-Wardrobe': 'Armoire en Bois',
    'default-TV Stand': 'Meuble TV',
    'default-TV': 'Téléviseur',
    'default-Bathtub': 'Baignoire Douche'
  },
  'ja': {
    'default-Bed': 'ダブルベッド',
    'default-StudyDesk': '学習机',
    'default-chair': '椅子',
    'default-Table': 'ローテーブル',
    'default-Bedsidetable': 'サイドテーブル左',
    'default1-Bedsidetable': 'サイドテーブル右',
    'default-lamp': 'ランプ左',
    'default-Bedsidelamp': 'ランプ右',
    'default-sofa': 'メインソファ',
    'default1-sofa': 'アームチェアA',
    'default2-sofa': 'アームチェアB',
    'default-wasthsink': '洗面台',
    'default-Toilet': 'トイレ',
    'default-kitchenStuie': 'システムキッチン',
    'default-Refrigerator': '冷蔵庫',
    'default1-Wardrobe': '白いワードローブ',
    'default-Wardrobe': '木製ワードローブ',
    'default-TV Stand': 'テレビ台',
    'default-TV': 'テレビ',
    'default-Bathtub': 'シャワー浴槽'
  },
  'es': {
    'default-Bed': 'Cama Doble',
    'default-StudyDesk': 'Escritorio',
    'default-chair': 'Silla',
    'default-Table': 'Mesa de Centro',
    'default-Bedsidetable': 'Mesita de Noche I',
    'default1-Bedsidetable': 'Mesita de Noche D',
    'default-lamp': 'Lámpara I',
    'default-Bedsidelamp': 'Lámpara D',
    'default-sofa': 'Sofá Principal',
    'default1-sofa': 'Sillón A',
    'default2-sofa': 'Sillón B',
    'default-wasthsink': 'Lavabo',
    'default-Toilet': 'Inodoro',
    'default-kitchenStuie': 'Cocina Integrada',
    'default-Refrigerator': 'Nevera',
    'default1-Wardrobe': 'Armario Blanco',
    'default-Wardrobe': 'Armario de Madera',
    'default-TV Stand': 'Mueble TV',
    'default-TV': 'Televisión',
    'default-Bathtub': 'Bañera Ducha'
  }
};

export const INITIAL_INVENTORY: ReceiptItem[] = [
  {
    id: 'default-Bed',
    name: 'Standard Bed',
    translatedName: '双人床',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 7, y: 6 },
    rotation: 0,
    scale: 1.7,
    heightScale: 1.7,
    elevation: 0,
    voxelModel: standardBed as unknown as VoxelModel
  },
  {
    id: 'default-StudyDesk',
    name: 'Study Desk',
    translatedName: '学习桌',
    emoji: '✏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 120 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 5, y: 18 },
    rotation: 180,
    scale: 1.1,
    heightScale: 1.2,
    elevation: 0,
    voxelModel: studyDesk as unknown as VoxelModel
  },
  {
    id: 'default-chair',
    name: 'Study Chesk',
    translatedName: '椅子',
    emoji: '🪑',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 20 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 5, y: 16 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.7,
    elevation: 0,
    voxelModel: chair as unknown as VoxelModel
  },
  {
    id: 'default-Table',
    name: 'Sofa Table',
    translatedName: '茶几',
    emoji: '🥃',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 31 },
    rotation: 0,
    scale: 1.25,
    heightScale: 1.0,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default-Bedsidetable',
    name: 'Bedside Table',
    translatedName: '床头柜',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 10 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 11, y: 4 },
    rotation: 0,
    scale: 0.6,
    heightScale: 1.75,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default1-Bedsidetable',
    name: 'Bedside mini Table',
    translatedName: '小床头柜',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 10 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 3, y: 4 },
    rotation: 0,
    scale: 0.6,
    heightScale: 1.75,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default-lamp',
    name: 'Bedside lamp',
    translatedName: '床头灯',
    emoji: '💡',
    unit: '台',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 5 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 11, y: 4 },
    rotation: 0,
    scale: 0.35,
    heightScale: 1.65,
    elevation: 23,
    voxelModel: classicalLamp as unknown as VoxelModel
  },
  {
    id: 'default-Bedsidelamp',
    name: 'Bedside mini lamp',
    translatedName: '小床头灯',
    emoji: '💡',
    unit: '台',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 5 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 3, y: 4 },
    rotation: 0,
    scale: 0.35,
    heightScale: 1.65,
    elevation: 23,
    voxelModel: classicalLamp as unknown as VoxelModel
  },
  {
    id: 'default-sofa',
    name: 'Lux Sofa',
    translatedName: '沙发',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 28, y: 31 },
    rotation: 270,
    scale: 1.65,
    heightScale: 1.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default1-sofa',
    name: 'Single Sofa',
    translatedName: '单人沙发',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 38 },
    rotation: 180,
    scale: 1.0,
    heightScale: 2.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default2-sofa',
    name: 'Single preson Sofa',
    translatedName: '单沙发',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 24 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default-wasthsink',
    name: 'Wash Basin',
    translatedName: '实木洗手台',
    emoji: '🛀',
    unit: '台',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 34, y: 13 },
    rotation: 90,
    scale: 0.9,
    heightScale: 2.05,
    elevation: 0,
    voxelModel: bathroomVanity as unknown as VoxelModel
  },
  {
    id: 'default-Toilet',
    name: 'Simple Toilet',
    translatedName: '马桶',
    emoji: '🚽',
    unit: '個',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 34, y: 4 },
    rotation: 180,
    scale: 1.2,
    heightScale: 2.5,
    elevation: 0,
    voxelModel: simpleToilet as unknown as VoxelModel
  },
  {
    id: 'default-kitchenStuie',
    name: 'Kitchen Stuie',
    translatedName: '组合厨房',
    emoji: '🍳',
    unit: '组',
    assignedRoom: 'kitchen',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 4, y: 28 },
    rotation: 270,
    scale: 1.6,
    heightScale: 2.4,
    elevation: 0,
    voxelModel: luxuryKitchenSuite as unknown as VoxelModel
  },
  {
    id: 'default-Refrigerator',
    name: 'Modern Refrigerator',
    translatedName: '冰箱',
    emoji: '⬜',
    unit: '台',
    assignedRoom: 'kitchen',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 14, y: 24 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.4,
    elevation: 0,
    voxelModel: modernRefrigerator as unknown as VoxelModel
  },
  {
    id: 'default1-Wardrobe',
    name: 'standard Wardrobe',
    translatedName: '白衣柜',
    emoji: '👚',
    unit: '個',
    assignedRoom: 'cloakroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 18, y: 7 },
    rotation: 90,
    scale: 1.6,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: minimalistFourDoorWardrobe as unknown as VoxelModel
  },
  {
    id: 'default-Wardrobe',
    name: 'Minimalist Wardrobe',
    translatedName: '木制衣柜',
    emoji: '👚',
    unit: '個',
    assignedRoom: 'cloakroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 18, y: 14 },
    rotation: 90,
    scale: 1.6,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: minimalistFourDoorWardrobe as unknown as VoxelModel
  },
  {
    id: 'default-TV Stand',
    name: 'Minimalist TV Stand',
    translatedName: '电视柜',
    emoji: '🔲',
    unit: '台',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 42, y: 30 },
    rotation: 90,
    scale: 2.1,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: modernTVStand as unknown as VoxelModel
  },
  {
    id: 'default-TV',
    name: 'standard TV',
    translatedName: '电视',
    emoji: '📺',
    unit: '台',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 199 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 42, y: 31 },
    rotation: 90,
    scale: 2.0,
    heightScale: 2.6,
    elevation: 52,
    voxelModel: minimalistTV as unknown as VoxelModel
  },
  {
    id: 'default-Bathtub',
    name: 'Shower Bathtub',
    translatedName: '淋浴',
    emoji: '🚿',
    unit: '個',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 26, y: 6 },
    rotation: 90,
    scale: 1.7,
    heightScale: 1.8,
    elevation: 0,
    voxelModel: showerBathtub as unknown as VoxelModel,
  }
];
