import { ReceiptItem } from './geminiService';
import { VoxelModel } from './voxelTypes';
import { bathroomVanity } from './blueprints/bathroomVanity';
import { sofa } from './blueprints/sofa';
import { minimalistFourDoorWardrobe } from './blueprints/minimalistFourDoorWardrobe';
import { luxuryKitchenSuite } from './blueprints/luxuryKitchenSuite';
import { modernRefrigerator } from './blueprints/modernRefrigerator';
import { showerBathtub } from './blueprints/showerBathtub';
import { modernTVStand } from './blueprints/modernTVStand';
import { minimalistTV } from './blueprints/minimalistTV';
import { standardBed } from './blueprints/standardBed';
import { bedsideTable } from './blueprints/bedsideTable';
import { classicalLamp } from './blueprints/classicalLamp';
import { studyDesk } from './blueprints/studyDesk';
import { simpleToilet } from './blueprints/simpleToilet'; 
import { chair } from './blueprints/chair'; 

export const INITIAL_INVENTORY: ReceiptItem[] = [
  {
    id: 'default-Bed',
    name: 'Standard Bed',
    translatedName: '床',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 7, y: 6 },
    rotation: 0,
    scale: 1.7,
    heightScale: 1.7,
    elevation: 0,
    voxelModel: standardBed as unknown as VoxelModel
  },
  {
    id: 'default-StudyDesk',
    name: 'Study Desk',
    translatedName: '學習桌',
    emoji: '✏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 120 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 5, y: 18 },
    rotation: 180,
    scale: 1.1,
    heightScale: 1.2,
    elevation: 0,
    voxelModel: studyDesk as unknown as VoxelModel
  },
  {
    id: 'default-chair',
    name: 'Study Chesk',
    translatedName: '椅子',
    emoji: '🪑',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 20 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 5, y: 16 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.7,
    elevation: 0,
    voxelModel: chair as unknown as VoxelModel
  },
  {
    id: 'default-Table',
    name: 'Sofa Table',
    translatedName: '茶几',
    emoji: '🥃',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 31 },
    rotation: 0,
    scale: 1.25,
    heightScale: 1.0,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default-Bedsidetable',
    name: 'Bedside Table',
    translatedName: '床頭櫃',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 10 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 11, y: 4 },
    rotation: 0,
    scale: 0.6,
    heightScale: 1.75,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default1-Bedsidetable',
    name: 'Bedside mini Table',
    translatedName: '小床頭櫃',
    emoji: '🛏️',
    unit: '張',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 10 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 3, y: 4 },
    rotation: 0,
    scale: 0.6,
    heightScale: 1.75,
    elevation: 0,
    voxelModel: bedsideTable as unknown as VoxelModel
  },
  {
    id: 'default-lamp',
    name: 'Bedside lamp',
    translatedName: '床頭燈',
    emoji: '💡',
    unit: '台',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 5 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 11, y: 4 },
    rotation: 0,
    scale: 0.35,
    heightScale: 1.65,
    elevation: 23,
    voxelModel: classicalLamp as unknown as VoxelModel
  },
  {
    id: 'default-Bedsidelamp',
    name: 'Bedside mini lamp',
    translatedName: '小床頭燈',
    emoji: '💡',
    unit: '台',
    assignedRoom: 'bedroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 5 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 3, y: 4 },
    rotation: 0,
    scale: 0.35,
    heightScale: 1.65,
    elevation: 23,
    voxelModel: classicalLamp as unknown as VoxelModel
  },
  {
    id: 'default-sofa',
    name: 'Lux Sofa',
    translatedName: '沙發',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 28, y: 31 },
    rotation: 270,
    scale: 1.65,
    heightScale: 1.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default1-sofa',
    name: 'Single Sofa',
    translatedName: '單人沙發',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 38 },
    rotation: 180,
    scale: 1.0,
    heightScale: 2.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default2-sofa',
    name: 'Single preson Sofa',
    translatedName: '單沙發',
    emoji: '🛋️',
    unit: '張',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 50 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 35, y: 24 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.0,
    elevation: 0,
    voxelModel: sofa as unknown as VoxelModel
  },
  {
    id: 'default-wasthsink',
    name: 'Wash Basin',
    translatedName: '实木洗手台',
    emoji: '🛀',
    unit: '台',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 34, y: 13 },
    rotation: 90,
    scale: 0.9,
    heightScale: 2.05,
    elevation: 0,
    voxelModel: bathroomVanity as unknown as VoxelModel
  },
  {
    id: 'default-Toilet',
    name: 'Simple Toilet',
    translatedName: '馬桶',
    emoji: '🚽',
    unit: '個',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 34, y: 4 },
    rotation: 180,
    scale: 1.2,
    heightScale: 2.5,
    elevation: 0,
    voxelModel: simpleToilet as unknown as VoxelModel
  },
  {
    id: 'default-kitchenStuie',
    name: 'Kitchen Stuie',
    translatedName: '组合厨房',
    emoji: '🍳',
    unit: '组',
    assignedRoom: 'kitchen',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 7, y: 29 },
    rotation: 270,
    scale: 1.6,
    heightScale: 2.4,
    elevation: 0,
    voxelModel: luxuryKitchenSuite as unknown as VoxelModel
  },
  {
    id: 'default-Refrigerator',
    name: 'Modern Refrigerator',
    translatedName: '冰箱',
    emoji: '⬜',
    unit: '台',
    assignedRoom: 'kitchen',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 14, y: 24 },
    rotation: 0,
    scale: 1.0,
    heightScale: 2.4,
    elevation: 0,
    voxelModel: modernRefrigerator as unknown as VoxelModel
  },
  {
    id: 'default-Wardrobe',
    name: 'Minimalist Wardrobe',
    translatedName: '木製衣櫃',
    emoji: '👚',
    unit: '個',
    assignedRoom: 'cloakroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 18, y: 7 },
    rotation: 90,
    scale: 1.6,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: minimalistFourDoorWardrobe as unknown as VoxelModel
  },
  {
    id: 'default-Wardrobe',
    name: 'Minimalist Wardrobe',
    translatedName: '木製衣櫃',
    emoji: '👚',
    unit: '個',
    assignedRoom: 'cloakroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 18, y: 14 },
    rotation: 90,
    scale: 1.6,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: minimalistFourDoorWardrobe as unknown as VoxelModel
  },
  {
    id: 'default-TV Stand',
    name: 'Minimalist TV Stand',
    translatedName: '電視櫃',
    emoji: '🔲',
    unit: '台',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 100 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 42, y: 30 },
    rotation: 90,
    scale: 2.1,
    heightScale: 2.6,
    elevation: 0,
    voxelModel: modernTVStand as unknown as VoxelModel
  },
  {
    id: 'default-TV',
    name: 'standard TV',
    translatedName: '電視',
    emoji: '📺',
    unit: '台',
    assignedRoom: 'living',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 199 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 42, y: 31 },
    rotation: 90,
    scale: 2.0,
    heightScale: 2.6,
    elevation: 52,
    voxelModel: minimalistTV as unknown as VoxelModel
  },
  {
    id: 'default-wasthsink',
    name: 'Wash Basin',
    translatedName: '实木洗手台',
    emoji: '🛀',
    unit: '台',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 34, y: 13 },
    rotation: 90,
    scale: 0.9,
    heightScale: 2.05,
    elevation: 0,
    voxelModel: bathroomVanity as unknown as VoxelModel
  },
  {
    id: 'default-Bathtub',
    name: 'Shower Bathtub',
    translatedName: '淋浴',
    emoji: '🚿',
    unit: '個',
    assignedRoom: 'bathroom',
    history: [{ timestamp: 1715000000000, quantity: 1, unitPrice: 0 }],
    currentQuantity: 1,
    showOnMap: true,
    position: { x: 25, y: 6 },
    rotation: 90,
    scale: 1.7,
    heightScale: 1.8,
    elevation: 0,
    voxelModel: showerBathtub as unknown as VoxelModel,
  }
];